name: Build packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  tests:
    name: Test code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - ^1
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Install packaging dependencies
      run: |
        sudo apt-get install libcairo2-dev mercurial pkg-config wget -y
        gem install package_cloud
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test
      run: |
        make test
        make
        ./e2e_test.sh
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create packages
      env:
        BUILD_PACKAGES: true
        PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      run: |
        wget "https://raw.githubusercontent.com/go-graphite/helper-scripts/main/build.sh" && chmod +x ./build.sh
        ./build.sh carbonapi
